algoritmo "correçãodaatividade1"
var
   numero, antecessor : INTEIRO

inicio
//1) Escreva um algoritmo para ler um valor e escrever seu antecessor
//ENTRADA
//RECEBER UM NUMERO
          escreva("Digite um número para verificar antecessor: ")
          leia(numero)


//PROCESSO
//NUMERO -1
         antecessor <-(numero-1)


//SAIDA
//ESCREVER O ANTECESSOR
           LimpaTela
           escreval("O antecessor de ", numero, " é: ", antecessor)



fimalgoritmo